name: On Release Workflow

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update 'version' file
        run: |
          export VERSION="${{ github.event.release.tag_name }}"
          echo "$VERSION" > version
          sed -i "s/^version:.*$/version: ${VERSION:1}/" charts/gubernator/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: ${VERSION:1}/" charts/gubernator/Chart.yaml
   
      # Buildx Needs QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # We use Buildx so we can take advantage of the caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/zoom/gubernator:${{ github.event.release.tag_name }}
            ghcr.io/zoom/gubernator:latest
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
          push: true           
      
      # Commit the updated 'version' file
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update version number'
          branch: master
          add: '["version", "charts/gubernator/Chart.yaml"]'

      # Publish the Helm chart
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
